config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/', to: 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :books do
     resources :reviews
  end

  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'



  resources :users, except: [:new]

  # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable'

end

app/models/user.rb


class EmailformatValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end





class User < ApplicationRecord
  has_many :books
  has_many :reviews
  before_save {self.email = email.downcase}

  validates :username, presence: true, uniqueness: {case_sensitive: false},
            length: {minimum:4, maximum: 25}
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: {message: "you should enter a valid email"},  uniqueness: {case_sensitive: false, message: "this email exist in our database"}, emailformat: true     #format: {with: VALID_EMAIL_REGEX}
  has_secure_password

  def new_record?
    id == nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show, :index, :new, :create]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin_user, only: [:destroy]


  def show
  end

  def new
    @user = User.new
  end

  def create
    debugger
    @user = User.new(user_params)
    if @user.save
      flash[:noticed] = "Welcome to book review site #{@user.username}"
        redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
    if @user.update(user_params)
      flash[:noticed] = "user is updated successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:noticed] = "you're successfully signed up"
        redirect_to login_path()
    else
      render :new
    end
  end

  def destroy
    @username = @user.username
    @user.destroy
    flash[:noticed] = "user "+ @username +" is deleted successfully"
    redirect_to users_path
  end


  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger]= "you can perform this action only if you're the one who wrote this review!"
        redirect_to root_path
      end
    end
  end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg|%>
    <li><%= msg%></li>
    <% end %>
  </ul>
<% end %>



<%= simple_form_for @user  do |u| %>  <!--:as => :user, :url => signup_path(@user) do |u|  %-->
  <div style="margin-top: 20px;">
    <%= u.label :username %></label><br/>
    <%= u.text_field :username%>
  </div>

  <div style="margin-top: 20px;">
    <%= u.label :email %></label><br/>
    <%= u.email_field :email%>
  </div>

  <div style="margin-top: 20px;">
    <%= u.label :password %></label><br/>
    <%= u.password_field :password%>
  </div>

  <div style="margin-top: 20px;">
    <% if @user.new_record?%>
      <%=u.submit "sign up"%>
    <%else%>
      <%=u.submit "update account"%>
    <%end%>
  </div>
<% end %>

<div style="margin-top: 30px;">
<%= link_to 'back to list of books', books_path%>
</div>

app/views/users/edit.html.erb
<h1>Modify user information</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<table style=" width: 50%;">
  <tr>
    <th>User Name</th>
    <th>Email</th>
  </tr>
<%User.all.each do |u|%>
   <tr>
     <td> <%= u.username %></td>
     <td> <%= u.email%></td>

     <td> <%= link_to 'Display', user_path(u)%></td>
     <td>
      <%if logged_in? && (current_user == u || is_Admin_user?)  %>
         <%= link_to 'Edit', edit_user_path(u) %>
      <%end%>
      </td>
      <td>
      <%if is_Admin_user? %>
        <%= link_to 'Delete' , user_path(u), method: :delete, data: {confirm: 'Are you suire you want to delete this user?'} %>
      <%end%>
      </td>
   </tr>
<%end%>
</table>

app/views/users/new.html.erb
<h1>Sing up for book review</h1>

<%= render 'form'%>

app/views/users/show.html.erb
<h1> information of user </h1>

<div >
  <br/>
  <div style="margin-top: 20px;">
    Username:  <%= @user.username%>
  </div>
  <div style="margin-top: 20px;">
    Email:  <%= @user.email%>
  </div>
  <div style="margin-top: 20px;">
    Created at:  <%= @user.created_at.to_date%>
  </div>
  <div style="margin-top: 20px;margin-bottom:20px">
  <%= link_to 'Back to list of books', books_path%>
  </div>
</div>


<div>
<div style=" width: 50%; float:left">
  <h3>Books created by this user</h3>
  <div style=" width: 75%;">
    <table>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Overall Rate</th>
        <th/>
        <th/>
      </tr>
    <%@user.books.each do |b|%>
       <tr>
         <td> <%= b.title %></td>
         <td> <%= b.author%></td>
         <td> <%= b.rate%></td>
         <td>
           <%= link_to 'Display', book_path(b)%>|<%= link_to 'Add a rewview', new_book_review_path(b)%>
         </td>
         <td>
           <%if logged_in? && (current_user == b.user || is_Admin_user?) %>
             <%= link_to 'Edit', edit_book_path(b) %>
           <%end%>
           <%if is_Admin_user? %>
             |<%= link_to 'Delete' , book_path(b), method: :delete, data: {confirm: 'Are you suire you want to delete this book?'} %>
           <%end%>
         </td>
       </tr>
    <%end%>
    </table>
  </div>
</div>


<div style=" width: 50%; float:right">
<h3>Reviews of this user</h3>
<table>
  <tr>
    <th>Book title</th>
    <th>Author</th>
    <th>Rate</th>
    <th>review</th>
  </tr>
  <% @user.reviews.each do |r| %>
  <tr>
    <td style="width: 15%";><%=r.book.title%> </td>
    <td style="width: 15%";><%=r.book.author%> </td>
    <td style="width: 5%; text-align:center;"><%=r.rate%> </td>
    <td style="width: 55%;"><%= r.review %></td>
    <td>
      <%if logged_in? && (current_user == r.user || is_Admin_user?) %>
        <%= link_to 'Edit', edit_book_review_path(r.book, r)  %>
        <%= link_to 'Delete', book_review_path(r.book, r),  method: :delete, data: {confirm: 'Are you suire you want to delete this book?'} %>
      <%end%>
    </td>
  </tr>
  <%end%>
</table>
</div>
</div<