config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/', to: 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :books do
     resources :reviews
  end

  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'



  resources :users, except: [:new]

  # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable'

end

app/models/book.rb
class Book < ApplicationRecord #ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  validates :title, presence: true, uniqueness: true, length: {minimum:3, maximum:60 }
  validates :author, presence: true, length: {minumum: 4, maximum: 100}
  #validates :user_id, presence: true

  def rate
    sum = 0
     reviews.each do |r|
       sum += r.rate
     end
     (sum.to_f / reviews.length).round(1)
  end


  after_commit {               
    MessageBroadcastJob.perform_later(self) 
  }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [ :edit, :destroy, :update]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin_user, only: [:destroy]
  before_action :require_user, except: [:show, :index]


  def index

    if params[:sort]
      @books = Book.order(params[:sort] + ' ' + params[:direction])
    else
       @books =  Book.all
    end
    if params[:filter]
      @books = @books.find_all{|b| b.title.downcase.include? (params[:filter].downcase)}
    end
  end

  def show
    book = Book.find(params[:id])
      if params[:sort]
        book.reviews = []
        @reviews = Review.order(params[:sort] + ' ' + params[:direction])
        book.reviews = @reviews
      end
      @book = book
  end
#create new book __________________
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:noticed] = "book is saved successfully"
      redirect_to books_path
    else
      render :new
    end
  end

  #edit book
  def edit
  end

  def update
    if @book.update(book_params)
      flash[:noticed] = "book is updated successfully"
      redirect_to books_path
    else
      render :edit
    end
  end

def destroy
  @title = @book.title
  @book.destroy
  flash[:noticed] = "book "+ @title +" is deleted successfully"
  redirect_to books_path
end


private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author)
  end

  def require_same_user
    if  current_user == nil ||( current_user != @book.user && !current_user.admin?)
      flash[:danger]= "you can perform this action only if you're the one who wrote this review!"
      redirect_to root_path
    end
  end
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <ul>
    <% @book.errors.full_messages.each do |msg|%>
    <li><%= msg%></li>
    <% end %>
  </ul>
  <%= @book.title%>
<% end %>



<%= form_for @book do |b|  %>
  <div style="margin-top: 20px;">
    <%= b.label :title %></label><br/>
    <%= b.text_field :title%>
  </div>

  <div style="margin-top: 20px;">
    <%= b.label :author %></label><br/>
    <%= b.text_field :author%>
  </div>

  <div style="margin-top: 20px;">
    <%= b.submit%>
  </div>
<% end %>

<div style="margin-top: 50px;">
<%= link_to 'back to list of books', books_path%>
</div>

app/views/books/_grid.html.erb
<%= grid(@tasks_grid) do |g|

  g.column do |task|
    task.id
  end

  g.column  do |task|
    task.title
  end

  g.column do |task|
    task.authos
  end

  g.column do |task|
    task.created_at
  end

  #g.column do |task|
#    task.created_at.to_s(:short)
#  end

  g.column do |task|
    link_to('Edit', edit_task_path(task))
  end
end -%>

app/views/books/_index-partial.html.erb
<tr id= <%=b.id%> >
       <td class='id'> <%= b.id %></td>
       <td class='title'> <%= b.title %></td>
       <td class='author'> <%= b.author%></td>
       <td> <%= b.user.username if b.user%></td>
       <td> <%= b.created_at%></td>
       <td class='rate'> <%= b.rate%></td>

       <td> <%= link_to 'Display', book_path(b)%>
       <%if logged_in? %>
         |<%= link_to 'Add a review', new_book_review_path(b)%>
       <%end%>
       </td>
       <%if logged_in? && (current_user == b.user || is_Admin_user?)  %>
         <td> <%= link_to 'Edit', edit_book_path(b) %></td>
      <%end%>
         <%if is_Admin_user? %>
           <td> <%= link_to 'Delete' , book_path(b), method: :delete, data: {confirm: 'Are you suire you want to delete this book?'} %> </td>
       <%end%>
     </tr>

app/views/books/edit.html.erb
<h1>Edit existing book</h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1>List the books</h1>
<br/>
<br/>
<input type="text" data-behavior="room_speaker">
<br/>
<div id="messages">
<br/>
<p>
  <%if logged_in? %>
    <%= link_to 'Create new book', new_book_path %> <br/><br/>
  <%end%>
</p>

<div style=" width: 75%;">
  <table id="book_list">
    <tr>
      <th><%= sortable  'id', 'Order'%></th>
      <th><%= sortable  'title'%></th>
      <th><%= sortable  'author'%></th>
      <th>Created by</th>
      <th><%= sortable 'created_at', 'Created at' %></th>
      <th>Rate</th>
    </tr>

     <tr>
       <td> </td>
       <td>
         <%= form_tag books_path, method: "get" do %>
            <div style="float: left;"> <%= text_field_tag :filter %></div>
            <div style="float: left; padding-left:10px; text-color:Cyan "><%= submit_tag 'filter'%> </div>
         <% end %>
        </td>
       <td> </td>
       <td> </td>
       <td> </td>
       <td> </td>

     </tr>

  <%@books.each do |book|%>    
    
     <%= render :partial =>'index-partial', locals: {:b => book}  %>     

  <%end%>
  </table>
</div>

app/views/books/new.html.erb
<h1>Create a Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h1> Show selected book</h1>
<br/>
<div style=" width: 30%; float:left">
  <h2>Book information</h2>
<table>
  <tr>
    <td>  Title:   </td>
    <td style="font-weight: bold;" id="title">  <%= @book.title%>  </td> <td></td>
  </tr>
  <tr>
    <td>  Author:   </td>
    <td style="font-weight: bold;" id="author">  <%= @book.author%>  </td>
  </tr>
  <tr>
    <td>  Rate:   </td>
    <td style="font-weight: bold;" id="rate">  <%= @book.rate%>  </td>
  </tr>
  <tr>
    <td> created by:    </td>
    <td> <%= @book.user.username if @book.user%>   </td>
  </tr>
  <tr>
    <td> created at:  </td>
    <td>   <%= @book.created_at%>   </td>
  </tr>
  <tr>
    <td> modified at:  </td>
    <td>   <%= @book. updated_at%>   </td>
  </tr>
</table>

<p>
    <%if logged_in? %>
      <%= link_to 'Add e rewview', new_book_review_path(@book)%> |
    <%end%>
    <%if logged_in? && (current_user == @book.user ||  is_Admin_user?)%>
      <%= link_to 'Edit this book', edit_book_path(@book)%> |
    <%end%>
<%= link_to 'Back to list of books', books_path%>
</p>

</div>

<div style=" width: 65%; float:right">
<h2>Reviews</h2>
<table>
  <tr>
    <th><%= sortable 'rate' %></th>
    <th>By user</th>
    <th><%= sortable 'created_at', 'Created at' %></th>
    <th>review</th>
  </tr>
  <% @book.reviews.each do |r| %>
  <tr>
    <td style="width: 5%; text-align:center;"><%=r.rate%> </td>
    <td ><%=r.user.username if r.user%> </td>
    <td ><%=r.created_at.to_date%> </td>
    <td style="width: 60%;"><%= r.review %></td>
      <%if logged_in? && (current_user == r.user || is_Admin_user?) %>
        <td><%= link_to 'Edit', edit_book_review_path(r.book, r)  %></td>
        <td><%= link_to 'Delete', book_review_path(r.book, r),  method: :delete, data: {confirm: 'Are you suire you want to delete this book?'} %></td>
      <%else%>
      <td></td>
      <td></td>
     <%end%>

  </tr>
  <%end%>
</table>
</div>