config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/', to: 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :books do
     resources :reviews
  end

  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'



  resources :users, except: [:new]

  # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
   <li><%= msg %></li>
<% end %>

app/views/layouts/_navigation.html.erb



<nav class="navbar navbar-defaule " >
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button"
  data-toggle="collapse" data-target="#navbarSupportedContent"
  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" text="Click me">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <meta name="current-user" id="<%= current_user.id if current_user  %>">  
  </head>

  <body>  
    <div style="padding:25px">

      <div style="font-size:100%; font-weight: bold;" align="left">
        <%= link_to "Home", root_path%> |
        <%if logged_in? %>
          <%= link_to "logout", logout_path, method: :delete %> |
          <%= link_to "My profile", user_path(current_user)%>
        <% else %>
          <%=  link_to "log in", login_path %> |
          <%=  link_to "sign up", signup_path %>
        <%end%>
      </div>

      <br/>
      <br/>

      <%= render 'layouts/messages'%>
      <%= yield %>
   </div>

   <!--div style="height:30%; position:absolute; bottom:0px;">
      <br/><br/><br/><br/><br/><br/>
      <%= debug(params) if Rails.env.development? %>
  </div-->

  </body>
</html>